### ISSUE TITLE
SyntaxError in draw.io plugin

### ISSUE THREAD

**Issue by comvx** [ariel-bentu/tam-drawio#15]
It seems that there is a syntax error in the tam-drawio.js plugin for the desktop app. When restarting the app with the plugin added, one what receive the following console log. 

```
Message: Uncaught SyntaxError: Invalid or unexpected token 
URL: draw.io/plugins/tam-drawio.js
Line: 1 
Column: 13884 
Error: SyntaxError: Invalid or unexpected token
```

**Comment by ariel-bentu** [comment]
Hi, can you please add info such as:
- OS
- draw version
- does it work after this error, or this is a fatal error
- any special flow I should be aware of?

**Comment by comvx** [comment]
Sure,

- OS: Ventura 13.2
- Version: 20.8.16
- It does not work. The tools are not available (and neither can be added to the side panel on the left)
- Just add the plugin. Restart the app. Then I received the above mentioned console log/error message

**Comment by tonyhsap** [comment]
I get the same Error on my Mac:
OS: 13.3.1
DrawIO: 21.1.2

**Comment by ariel-bentu** [comment]
I have the same version and it works. I removed and added again and it works.

What looks weird is the fact that the error is in line 1 col 13884. Which means the whole file is somehow in one line.
Then I tried putting an error on purpose, for example, I put this line as line #2: `debugger();`
Then, I removed and added the tempered file tam-drawio.js, and this is the error I get:
```
Message: Uncaught SyntaxError: Unexpected token '(' 
URL: file:///Users/<my-user-id>/Library/Application%20Support/draw.io/plugins/tam-drawio.js 
Line: 2 
Column: 13 
Error: SyntaxError: Unexpected token '('
```

Which is different in two ways: (1) the exact path is visible (2) the file is not condensed into one line but kept as the source in github.

So, to try make progress here:
1) Locate the file in this path
2) See if it is indeed condensed
3) first try to replace it with the one from github and restart draw.io
4) if nothing helps, upload the bad file here so I can try run it and maybe understand how this happens.

Thanks

**Comment by tonyhsap** [comment]
I think I found the root cause of this error. On the page https://ariel-bentu.github.io/tam-drawio/ I used the button "Download TAM Plugin" in the "Destop App" section to download the js file. When I had a look at this file it seems to be cut off and as you said, it seems to be minified.

So I opened the js file from the Source Code and saved it as a js file (btw. it's 47KB in size, where the corrupt file was only 14KB in size). After I added the new file to Draw.io, it works just fine and I can see it in the Editor.

Could you please check the Download button on the github.io page?

Thanks
